apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-basico
  name: servicio-deployment-basico
spec:
  # indicando el tipo de conexión, en este caso NodePort
  type: NodePort
  ports:
  # Puerto que estamos exponiendo en el cluster
  - port: 7000
    protocol: TCP
    # Puerto que escucha nuestra aplicación en el contenedor.
    targetPort: 7000
    # Por defecto y por comodidad, el plano de control de Kubernetes asignará el puerto desde un rango (por defecto: 30000-32767)
    # nodePort: 30007
  selector:
    app: deployment-basico
  
status:
  loadBalancer: {}
  
