apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: netplan-config
data:
  01-network-manager-all.yaml: |
    # Let NetworkManager manage all devices on this system
    network:
      version: 2
      renderer: NetworkManager
