apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mi-secret
data:
  APP_PASSWORD: YWRtaW5hZG1pbg==
  APP_USUARIO: YWRtaW4=

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: app-secret
  name: pod-secret
spec:
  containers:
  - image: vacax/javalin-hola-mundo
    name: pod-secret
    ports:
    - containerPort: 7000
    #Indicando el nombre del puerto para luego reutilizalo en otras configuraciones.
      name: puerto-javalin
    # Estamos indicando una cantidad que estaremos dando al servicio.    
    resources:
      limits:
        cpu: 50m
        memory: 256M
      requests:
        cpu: 50m        
        memory: 256M
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: VARIABLE1
        valueFrom:
          # Indicando que estaremos haciendo referencia desde un objeto
          # tipo ConfigMap
          configMapKeyRef:
            # Indicando el nombre del configmap.
            name: mi-configmap
            # 
            key: VARIABLE1
      - name: VARIABLE2
        valueFrom:
          configMapKeyRef:
            name: mi-configmap
            key: VARIABLE2
      - name: APP_USUARIO
        valueFrom:
          secretKeyRef:
            name: mi-secret
            key: APP_USUARIO
      - name: APP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mi-secret
            key: APP_PASSWORD    
    livenessProbe:
      httpGet:
        path: /health
        port: puerto-javalin  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
