apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: configmap-archivo
  name: pod-configmap-archivo
spec:
  containers:
  - image: vacax/javalin-hola-mundo
    name: pod-configmap-archivo
    ports:
    - containerPort: 7000
    #Indicando el nombre del puerto para luego reutilizalo en otras configuraciones.
      name: puerto-javalin
    # Estamos indicando una cantidad que estaremos dando al servicio.    
    resources:
      limits:
        cpu: 50m
        memory: 256M
      requests:
        cpu: 50m        
        memory: 256M
    # Indicando     
    volumeMounts:
      - name: volumen-configmap
        mountPath: /tmp/
    livenessProbe:
      httpGet:
        path: /health
        port: puerto-javalin
  volumes:
    - name: volumen-configmap
      # Indicando que obtendrá el valor desde del Configmap.
      configMap:
        name: netplan-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
