apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hola-mundo
  name: pod-sin-recursos
spec:
  containers:
  - image: vacax/javalin-hola-mundo
    name: hola-mundo
    ports:
    - containerPort: 7000
    # Estamos indicando una cantidad exagerada de memoria.
    # El Pod no puede crearse dado que no existen recursos para asignar
    resources:
      limits:
        cpu: 50m
        memory: 20G
      requests:
        cpu: 50m        
        memory: 20G
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
