apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    # Los estaremos utilizando para filtrar las peticiones.
    app: basico
  name: pod-para-servicio
spec:
  containers:
  - image: vacax/javalin-hola-mundo
    name: pod-para-servicio
    ports:
    - containerPort: 7000
    #Indicando el nombre del puerto para luego reutilizalo en otras configuraciones.
      name: puerto-javalin
    # Estamos indicando una cantidad que estaremos dando al servicio.    
    resources:
      limits:
        cpu: 50m
        memory: 256M
      requests:
        cpu: 50m        
        memory: 256M
    # Validando que la aplicación esté funcionando.
    # La aplicación está configurada para fallar y reinicar el pod    
    livenessProbe:
      httpGet:
        path: /health
        port: puerto-javalin
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
