apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: basico
  name: pod-para-servicio
spec:
  ports:
  # Puerto que estamos exponiendo en el cluster
  - port: 7000
    protocol: TCP
    # Puerto que escucha nuestra aplicación en el contenedor.
    targetPort: 7000
  selector:
    app: basico
status:
  loadBalancer: {}
# Por defecto el tipo de conexión es ClusterIP.
